# Configuration Azure ML pour Streamlit Cloud
# Ces secrets sont configurés dans l'interface Streamlit Cloud

[azure_ml]
endpoint_url = "https://clip-pytorch-endpoint.azureml.inference.net/score"
api_key = "your-api-key"
model_type = "pytorch"
endpoint_name = "clip-pytorch-endpoint"

# Configuration de l'application
[app]
name = "Classification de Produits CLIP"
description = "Application de classification de produits utilisant le modèle CLIP PyTorch finetuné sur Azure ML"
version = "2.0.0"
