# Configuration Azure ML pour Streamlit Cloud
# Ces secrets sont configurés dans l'interface Streamlit Cloud

[azure_ml]
endpoint_url = "https://new-clip-classification-app-hrgracfqaegbd9ek.francecentral-01.azurewebsites.net/score"
api_key = "dummy_key"
model_type = "pytorch"
endpoint_name = "clip-pytorch-endpoint"

# Configuration de l'application
[app]
name = "Classification de Produits CLIP"
description = "Application de classification de produits utilisant le modèle CLIP PyTorch finetuné sur Azure ML"
version = "2.0.0"
